package model;

public enum TokenType {
    //KEYWORDS
    AUTO, BOOL, BREAK, CASE, CHAR, CONST, CONTINUE, DEFAULT, DO,
    DOUBLE, ELSE, ENUM, EXTERN, FLOAT, FOR, GOTO, IF,
    INT, LONG, REGISTER, RETURN, READ, SHORT, SIGNED, SIZEOF, STATIC,
    STRUCT, SWITCH, TYPEDEF, UNION, UNSIGNED, VOID, VOLATILE, WHILE, WRITE,
    //PRE-PROCESSING POLICES
    DEFINE, ELIF, PRE_IF, PRE_ELSE, ENDIF, ERROR, IFDEF, IF_NDEF, INCLUDE, MESSAGE, UNDEF,
    //ARITHMETIC OPS
    PLUS, MINUS, MULTI, DIV, MOD, INCREASE, DECREASE, INT_NUM, DECIMAL_NUM, TEXT, ID,
    //LOGIC OPS
    AND_AND, OR_OR, NOT_OP,
    //BIT LOGIC OPS
    AND_OP, OR_OP, BIT_NOT_OP, XOR_OP, SHL_OP, SHR_OP,
    //RELATIONAL OPS
    GT, LT, EQ, NOT_EQ, LT_EQ, GT_EQ,
    //GROUPING OPS
    L_BRACE, R_BRACE, L_SQUARE, R_SQUARE, L_PAR, R_PAR, COMMA, SEMI, COLON,
    //OTHERS
    ASSIGN, POINT, R_ARROW, DQ_MARK, QMARK, FRM_INT, FRM_DEC, FRM_STR,
    //ESCAPE CHARS
    NEW_LINE, END_STR, START_STR, H_TAB, V_TAB, LIT_BACKSLASH, LIT_DQ_MARK,
    ALERT, NEW_PAGE,
    //DEFAULT
    NOT_FOUND
}
